### PR TITLE
Fix incorrect API call to list roles 

### PR DESCRIPTION
**Pull request by PasinduYeshan**
### Purpose
This PR addresses following issues
- https://github.com/wso2/product-is/issues/17983
- https://github.com/wso2/product-is/issues/17968
- Something went wrong issue when goes to group section of `system` role in sub organization.

### Related Issues
- https://github.com/wso2/product-is/issues/17983
- https://github.com/wso2/product-is/issues/17968

### Related PRs
- None

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on the final implementation.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Integration tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

**Comment by SujanSanjula96** [comment]
Should we need to preserve backward compatibility here with legacy authz runtime? @sadilchamishka @AnuradhaSK

**Comment by PasinduYeshan** [comment]
Inside the `getRoleList` method it check if this is legazy authz runtime or not
```
export const getRolesList = (domain: string): Promise<RoleListInterface | any> => {

    const requestConfig: RequestConfigInterface = {
        headers: {
            "Content-Type": "application/json"
        },
        method: HttpMethods.GET,
        params: {
            domain
        },
        url: isLegacyAuthzRuntime() ?
            store.getState().config.endpoints.roles : store.getState().config.endpoints.rolesV2
    };
    ```
https://github.com/PasinduYeshan/wso2-identity-apps/blob/10ede532eb292ba7b27f2e1bdbeda6595244de87/apps/console/src/features/roles/api/roles.ts#L456

**Comment by SujanSanjula96** [comment]
@PasinduYeshan Still we need to call organization roles endpoint in else block in legacy authz runtime. Correct me if I am wrong @AnuradhaSK @sadilchamishka

**Comment by sadilchamishka** [comment]
> Should we need to preserve backward compatibility here with legacy authz runtime? @sadilchamishka @AnuradhaSK

yes. The PR will be updated accordingly.

**Review by brionmario — APPROVED** [review]

**Pull request merged**
