### PR TITLE
Fix i18n not working in extended files issue

### PR DESCRIPTION
**Pull request by geve82**
## Purpose
Resolves wso2/product-is#9299

## Goals
Manage extensions the same as original includes.

## Approach
Includes of extensions is managed by this pattern:

`
    <%
        File headerFile = new File(getServletContext().getRealPath("extensions/header.jsp"));
        if (headerFile.exists()) {
    %>
        <jsp:include page="extensions/header.jsp"/>
    <% } else { %>
        <jsp:directive.include file="includes/header.jsp"/>
    <% } %>
`

extensions/header.jsp is included statically whereas includes/header.jsp is resolved before been included. Change the pattern for both to be done the same: 

`
    <%
        File headerFile = new File(getServletContext().getRealPath("extensions/header.jsp"));
        if (headerFile.exists()) {
    %>
        <jsp:directive.include file="extensions/header.jsp"/>
    <% } else { %>
        <jsp:directive.include file="includes/header.jsp"/>
    <% } %>
`

### CODE REVIEW

**Comment by brionmario** [comment]
@somindatommy Would you be able to review this PR?

**Review by somindatommy — APPROVED** [review]

**Comment by thivi** [comment]
Hi Gregory Eve,
Thank you so much for your contribution. Even though your solution fixes the issue, it throws a file-not-found error when the extensions directory is not there or the directory is empty. 

This is because `directive.include` tries to include the file during translation and not during runtime. Since our condition to check if the file exists is only applicable during runtime we get this error.

To resolve this, I have included the `localize.jsp`file in the files in the includes directory and have replaced all instances of `directive.include` with `include` except for a few files. 

The PR with these changes is avalaible here. https://github.com/wso2/identity-apps/pull/1204

**Review by thivi — CHANGES_REQUESTED** [review]
Hi Gregory Eve,
Thank you so much for your contribution. Even though your solution fixes the issue, it throws a file-not-found error when the extensions directory is not there or the directory is empty.

This is because `directive.include` tries to include the file during translation and not during runtime. Since our condition to check if the file exists is only applicable during runtime we get this error.

To resolve this, I have included the `localize.jsp` file in the files in the includes directory and have replaced all instances of `directive.include` with `include` except for a few files (those that don't need the `localize.jsp`).

```jsp
    <%
        File headerFile = new File(getServletContext().getRealPath("extensions/header.jsp"));
        if (headerFile.exists()) {
    %>
        <jsp:include page="extensions/header.jsp"/>
    <% } else { %>
        <jsp:include page="includes/header.jsp"/>
    <% } %>
```

I attempted these fixes in my local repo and you can refer to them here.
- https://github.com/thivi/identity-apps/blob/feature/issue_9299/apps/authentication-portal/src/main/webapp/login.jsp
- https://github.com/thivi/identity-apps/blob/feature/issue_9299/apps/authentication-portal/src/main/webapp/includes/header.jsp

We will highly appreciate it if you could make the above changes and update your PR on or before the 8th of October, 2020.

**Comment by geve82** [comment]
Hi @thivi,

thanks for the better solution I have reverted my commit, took your branch and fix a remaining issue. 
I have tested it on WSO2-IS-5.11.0-alpha.

**Review by thivi — APPROVED** [review]

**Comment by thivi** [comment]
Thank you, @geve82. I have approved your changes. We really appreciate your effort.

**Pull request merged**
