### PR TITLE
Add portugese-brazil language support to the portals

### PR DESCRIPTION
**Pull request by ayeshajay**
### Related Issues
- https://github.com/wso2/product-is/issues/18771

### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on the final implementation.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Integration tests provided. (Add links if there are any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

**Comment by Achintha444** [comment]
Add screen record of the language switching function in the login interface and my account.

**Comment by Achintha444** [comment]
Add changeset

**Comment by ayeshajay** [comment]
> Add screen record of the language switching function in the login interface and my account.


https://github.com/wso2/identity-apps/assets/51480027/7b0e7f08-b020-4735-bfb3-f30e8b7de74c

**Comment by ayeshajay** [comment]
> Add screen record of the language switching function in the login interface and my account.

https://github.com/wso2/identity-apps/assets/51480027/dd69364f-a0c2-4021-ad77-1186d118253a

**Review by Achintha444 — APPROVED** [review]

**Pull request merged**
