### PR TITLE
Upgrade project to nx v15

### PR DESCRIPTION
**Pull request by pavinduLakshan**
### Purpose

$subject

### Related Issues
- NA

### Related PRs
NA
- 

### Checklist
- [ ] e2e cypress tests locally verified.
- [x] Manual test round performed and verified.
- [ ] UX/UI review done on the final implementation.
- [ ] Documentation provided. (Add links if there are any)
- [ ] Unit tests provided. (Add links if there are any)
- [ ] Integration tests provided. (Add links if there are any)

### Security checks
- [X] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [X] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

**Comment by pavinduLakshan** [comment]
nx affected fails in v15.0.0 and the issue is fixed in 15.3.3[1]

[1] https://github.com/nrwl/nx/issues/13668

**Comment by JayaShakthi97** [comment]
> nx affected fails in v15.0.0 and the issue is fixed in 15.3.3[1]
> 
> [1] [nrwl/nx#13668](https://github.com/nrwl/nx/issues/13668)

Hi @pavinduLakshan,

Can't we upgrade to the v15.3.3 in that case?

**Comment by pavinduLakshan** [comment]
> ` [66975c5](/wso2/identity-apps/pull/6499/commits/66975c5be60996e6c558fef7e00d5cffd5d010c2)`

Fixed with [66975c5](https://github.com/wso2/identity-apps/pull/6499/commits/66975c5be60996e6c558fef7e00d5cffd5d010c2)

**Comment by pavinduLakshan** [comment]
> > nx affected fails in v15.0.0 and the issue is fixed in 15.3.3[1]
> > [1] [nrwl/nx#13668](https://github.com/nrwl/nx/issues/13668)
> 
> Hi @pavinduLakshan,
> 
> Can't we upgrade to the v15.3.3 in that case?

Fixed with [66975c5](https://github.com/wso2/identity-apps/pull/6499/commits/66975c5be60996e6c558fef7e00d5cffd5d010c2)

**Comment by pavinduLakshan** [comment]
Unit tests are failing probably due to either @nrwl/jest version upgrade or rollup upgrade.

**Review by brionmario — APPROVED** [review]

**Pull request merged**
