### PR TITLE
Change CONSUMER userstore domain to CUSTOMER-DEFAULT.

### PR DESCRIPTION
**Pull request by dewniMW**
### Checklist
- [ ] e2e cypress tests locally verified.
- [ ] Manual test round performed and verified.
- [ ] UX/UI review done on final implementation.
- [ ] Documentation provided. (Add links if there's any)
- [ ] Unit tests provided. (Add links if there's any)
- [ ] Integration tests provided. (Add links if there's any)

### Security checks
- [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines?
- [ ] Ran FindSecurityBugs plugin and verified report?
- [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

### CODE REVIEW

**Comment by darshanasbg** [comment]
@NipuniBhagya @jeradrutnam Why do we need to maintain this constant here?

**Comment by NipuniBhagya** [comment]
> @NipuniBhagya @jeradrutnam Why do we need to maintain this constant here?

This because we reuse some of the identity-apps components in the cloud console. There we have certain implementations where we are depending on the consumer user store name. (Ex: https://github.com/wso2/identity-apps/blob/e2840411c2dd8739b539b905371eae1c13368e0b/apps/console/src/features/users/components/user-sessions.tsx#L303)

**Comment by darshanasbg** [comment]
> apps components in the cloud console. There we have certain implementations where we are depending on the consumer user store name. (Ex:

If these 'certain implementations' are in identity-apps-extentions (but not in identity-apps) repo, can we move this constant to identity-apps-extensions?

If we have any implementations on identity-apps repo that depends on this constant, we have to revisit our approach.

**Comment by dewniMW** [comment]
This PR is not yet ready to be merged.

**Review by NipuniBhagya — APPROVED** [review]

**Pull request merged**
